({
    //name: "jrails/index",
    out: "../../../src/assets/script/vendor.js",
    //In RequireJS 2.0, "out" can be a function. For single JS file
    //optimizations that are generated by calling requirejs.optimize(),
    //using an out function means the optimized contents are not written to
    //a file on disk, but instead pass to the out function:
    /*out: function (text, sourceMapText) {
        //Do what you want with the optimized text here.
        //Starting in 2.1.10, if generateSourceMaps was set to true
        //and optimize: 'uglify2' was used ('uglify' in r.js 2.2+), then the
        //second argument to this function, sourceMapText, will be the text of
        //the source map.
    },*/
    baseUrl: "../../..",
    writeBuildTxt: true,
    paths: {
        jrails: 'node_modules/jrails/src',
        DirectorRouter: 'node_modules/director/build/director.min',
        lodash: 'node_modules/lodash/lodash.min',
        jquery: 'node_modules/jquery/dist/jquery.min',
        //text: '../module/app/text',
        twitterBootstrap: 'node_modules/bootstrap/dist/js/bootstrap.min',
        //redux: 'node_modules/redux/dist/redux.min',
        vue: 'node_modules/vue/dist/vue.min',
        //toastr: 'node_modules/toastr/build/toastr.min',
        toastr: 'node_modules/jrails/src/notify/toastrMock',
        jqueryUi: 'node_modules/jquery-ui/jquery-ui.min',
        //templates: '../module/app/view',
    },
    include: [
        'node_modules/requirejs/require',
        'DirectorRouter',
        'lodash',
        'jquery',
        'twitterBootstrap',
        'vue',
        'jqueryUi',
        'jrails/spa/router',
        'jrails/helper/php',
        'jrails/event/eventService',
        'jrails/helper/class',
        'jrails/helper/localStorage',
        'jrails/domain/baseLocalStorage',
        'jrails/kernel/container',
        'jrails/rest/client',
        'jrails/notify/notifyTypeEnum',
        'jrails/notify/notifyService',
        'jrails/notify/driver/toastrDriver',
        'jrails/bootstrap/modal/modalService',
        'jrails/vue/vm',
        'jrails/spa/layer',
        'jrails/spa/query',
        'jrails/spa/controllerFactory',
    ],
    //stubModules: ['jquery'],
    //cssIn: "path/to/main.css",
    //out: "path/to/css-optimized.css",
    shim: {
        'DirectorRouter': {
            exports: 'Router'
        },
        'lodash': {
            exports: '_'
        },
        'jquery': {
            exports: '$'
        },
        "jqueryUi": {
            exports: "$",
            deps: ['jquery']
        },
        "twitterBootstrap": {
            deps: ["jquery"]
        },
        'toastr': {
            exports: 'toastr',
            deps: ["jquery"]
        },
        'vue': {
            exports: 'Vue'
        },
    }
});
